---
name: 'deploy'

on:
  push:
    branches:
      - main

jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 12.22.x
      - name: npm
        run: npm install hexo-cli -g
      - name: npm
        run: npm install
      - name: Run script
        run: |
          sed -e "s*\${gitpass}*${{ secrets.GIT_URL }}*" _config_vars.yml | tee _config.yml
          hexo clean
          hexo generate
          hexo deploy
