---
name: 'deploy'

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: anthonyrussano/wiki-server:latest
      env:
        gitpass: ${{ secrets.GIT_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: ./dep
