on: push
name: Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Clean
      uses: heowc/action-hexo@main
      with:
        args: clean
    - name: Generate
      uses: heowc/action-hexo@main
      with:
        args: generate
    - name: Deploy
      uses: heowc/action-hexo@main
      env:
        EMAIL: me@anthonyrussano.com
        NAME: Anthony Russano
      with:
        args: deploy
