---
name: 'deploy'

on:
  push:
    branches:
      - main

jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  docker:
    runs-on: ubuntu-latest
    container:
      image: anthonyrussano/wiki-server:latest
      volumes:
        - ${{ github.workspace }}/public:/site/public
        - ${{ github.workspace }}/source:/site/source
      env:
        gitpass: ${{ secrets.GIT_URL }}
    steps:
      - name: Deploy
        run: |
         hexo clean && hexo generate && hexo deploy
